config/routes.rb
FlickFit::Application.routes.draw do
  devise_for :users

  resources :movies
  resources :reviews
  match 'home' => 'home#index'

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include PeerScoreCalculator
  include HomeHelper

  before_filter :authenticate_user!

  REVIEWS_PER_PAGE = 10
  DEFAULT_PAGE_NUMBER = 1

  def index
    @genre = Genre::Filters.include?(params[:genre]) ? params[:genre] : nil
    existing_reviews = (@genre.present? ? Review.with_movie_genre(@genre).uniq : Review).where(:user_id => current_user.id)
    movie_relation = @genre.present? ? Movie.with_genre(@genre) : Movie

    unreviewed_movies = existing_reviews.any? ? movie_relation.where("movies.id not in (?)", existing_reviews.collect {|review| review.movie_id}) : movie_relation.all

    new_reviews = []
    unreviewed_movies.uniq.each do |movie|
      new_reviews << Review.new(:movie => movie, :user => current_user)
    end

    all_reviews = sort_reviews((existing_reviews + new_reviews), params[:order_by], nil)
    current_page = params[:page].present? ? params[:page].to_i : DEFAULT_PAGE_NUMBER

    all_existing_reviews_for_user = Review.where(:user_id => current_user.id)

    @genres = Genre::Filters - ["Action", "Adventure"]
    @peer_scores = calculate_peer_scores all_existing_reviews_for_user

    @reviews = all_reviews.paginate(:page => current_page, :per_page => REVIEWS_PER_PAGE)
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def calculate_prediction_score review, scores_hash
    other_reviews = Review.where(:movie_id => review.movie_id)
    calculate_weighted_average(other_reviews, scores_hash) if !other_reviews.empty?
  end

  def calculate_average_score review
    reviews = Review.where(:movie_id => review.movie_id)
    return 0 unless reviews.any?
    ratings = reviews.collect {|rev| rev.rating}
    (ratings.sum / ratings.count).round(2)
  end

  def number_of_ratings_for movie
    Review.count(:conditions => {:movie_id => movie.id})
  end

  def sort_reviews reviews, order_by, direction
    ordering_callbacks = {
      "title" => lambda { |rs| reviews.sort_by {|review| review.movie.title }},
      "predicted rating" => lambda {|rs| reviews.sort_by {|review| calculate_prediction_score(review, @peer_scores) }},
      "average rating" => lambda {|rs| reviews.sort_by {|review| calculate_average_score(review) }}
    }

    if !order_by.nil?
      return ordering_callbacks[order_by].call(reviews)
    end

    return ordering_callbacks["title"].call(reviews)
  end

  private

  def calculate_weighted_average reviews, scores_hash
    weights = []
    products = []
    scores_hash.each do |user, peer_score|
      review = reviews.detect {|rev| rev.user_id == user.id}
      next unless review
      weight = peer_score**2 * review.confidence
      weights << weight
      products << (weight * review.rating)
    end
    return (products.sum / weights.sum).round(2) if !weights.empty? && !products.empty?
  end
end

app/views/home/_filters.html.erb
  <div class="sort_by">
    <div style="float:left">
      <%= link_to 'All', {:controller => 'home', :action => 'index'}, class: ('active-filter' unless @genre) %>
      <% @genres.each do |filter| %>
        <%= link_to filter, {:controller => 'home', :action => 'index', :genre => filter}, class: ('active-filter' if filter == @genre) %>
      <% end %>
    </div>

    <%= form_tag home_path, :method => 'get' do %>
      <span>Sort By:</span>
      <%= select_tag :order_by, options_for_select(["title", "predicted rating", "average rating"]), :id => "order_reviews" %>
    <% end %>
  </div>

app/views/home/_peer_scores.html.erb
<div class="peer_score_container">
  <h4>My peer fit scores (higher is closer):</h4>
  <% @peer_scores.each do |peer, score| %>
    <%= peer.email %> (<%= score %>)
  <% end %>
</div>

app/views/home/index.html.erb
<% [:info, :error].each do |key| %>
  <% if flash[key] %>
  <div class="<%= key %>" id="flash">
    <%= flash[key] %>
  </div>
  <% end %>
<% end %>

<%= render :partial => 'peer_scores' %>
<%= render :partial => 'filters' %>
<%= render :partial => 'reviews/review', :collection => @reviews %>

<%= will_paginate @reviews %>