config/routes.rb
FlickFit::Application.routes.draw do
  devise_for :users

  resources :movies
  resources :reviews
  match 'home' => 'home#index'

  root :to => 'home#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include PeerScoreCalculator

  before_filter :authenticate_user!
  before_filter :set_peer_scores, :only => [:create, :update, :destroy]

  def index
    @user = current_user
    existing_reviews = Review.where :user_id => @user.id
    movies = existing_reviews.any? ? Movie.where("id not in (?)", existing_reviews.collect {|review| review.movie_id}) : Movie.all


    new_reviews = []
    movies.each do |movie|
      new_reviews << Review.new(:movie => movie, :user => @user)
    end

    @reviews = (existing_reviews + new_reviews).sort_by {|review| review.movie.title}
  end

  def create
    review_params = params[:review]
    confidence = review_params[:confidence].present? ? review_params[:confidence] : Review::DEFAULT_CONFIDENCE
    @review = Review.new :movie_id => review_params[:movie_id], :rating => review_params[:rating], :confidence => confidence, :user_id => current_user.id
    @review.save unless review_params[:rating].blank?
    respond_to do |format|
      format.html { redirect_to home_path }
      format.js
    end
  end

  def update
    @review = Review.find_by_id params[:id]
    confidence = params[:review][:confidence].present? ? params[:review][:confidence] : Review::DEFAULT_CONFIDENCE
    modified_params = params[:review].merge({:user_id => current_user.id, :confidence => confidence})

    @review.update_attributes(modified_params)
    respond_to do |format|
      format.html { redirect_to home_path }
      format.js
    end
  end

  def destroy
    review = Review.find_by_id params[:id]
    @review = Review.new :movie => review.movie, :user => current_user
    review.destroy
    respond_to do |format|
      format.html { redirect_to home_path }
      format.js
    end
  end

private
  def set_peer_scores
    reviews = Review.where :user_id => current_user.id
    @peer_scores = calculate_peer_scores reviews
  end
end

app/views/reviews/_review.html.erb
<div id="review_for_movie_<%= review.movie_id %>">
  <%= form_for review, :remote => true, :namespace => "movie_#{review.movie_id}", :html => {:class => "review_container"} do |f| %>
    <%= render 'movies/movie', :movie => review.movie %>

    <%= f.hidden_field :movie_id %>
    <div class="ratings_container">
      <span style="font-weight:bold; font-size:.8em">
        Your Rating :
      </span>
      <%= f.radio_button :rating, 1.0 %>
      <%= f.label :rating, '1.0 (terrible)', :value => 1.0 %>
      <%= f.radio_button :rating, 1.5 %>
      <%= f.label :rating, '1.5', :value => 1.5 %>
      <%= f.radio_button :rating, 2.0 %>
      <%= f.label :rating, '2.0 (poor)', :value => 2.0 %>
      <%= f.radio_button :rating, 2.5 %>
      <%= f.label :rating, '2.5 (neutral)', :value => 2.5 %>
      <%= f.radio_button :rating, 3.0 %>
      <%= f.label :rating, '3.0 (decent)', :value => 3.0 %>
      <%= f.radio_button :rating, 3.5 %>
      <%= f.label :rating, '3.5', :value => 3.5 %>
      <%= f.radio_button :rating, 4.0 %>
      <%= f.label :rating, '4.0 (good)', :value => 4.0 %>
      <%= f.radio_button :rating, 4.5 %>
      <%= f.label :rating, '4.5', :value => 4.5 %>
      <%= f.radio_button :rating, 5.0 %>
      <%= f.label :rating, '5.0 (great)', :value => 5.0 %>
    </div>

    <div class="confidence_container">
      <span style="font-weight:bold; font-size:.8em">
        Confidence (how confident do you feel about that rating?):
      </span>
      <%= f.radio_button :confidence, 1 %>
      <%= f.label :confidence, 'weakly', :value => 1 %>
      <%= f.radio_button :confidence, 2 %>
      <%= f.label :confidence, 'moderately', :value => 2 %>
      <%= f.radio_button :confidence, 3 %>
      <%= f.label :confidence, 'strongly', :value => 3 %>
    </div>

    <% average_score = calculate_average_score(review) %>
    <% predicted_score = calculate_prediction_score(review, @peer_scores) %>
    <div>
      <span style="padding-right:20px">
        Average User Rating: <%= average_score %> (<%= number_of_ratings_for(review.movie) %> total ratings)
      </span>
      <span style="padding-right:20px">
        Predicted Rating: <%= predicted_score %>
      </span>
      <span>
        Difference: <%= (predicted_score - average_score).round(2) if predicted_score && average_score %>
      </span>
    </div>

    <% if review.id? %>
      <div>
        <%= link_to "delete", review_path(review), :method=>:delete, :remote=>true, :class=>"remove", :confirm=>'Delete this review?' %>

      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/create.js.erb
$("#review_for_movie_<%= @review.movie_id %>").html("<%= escape_javascript(render :partial => 'review', :object => @review) %>")

app/views/reviews/destroy.js.erb
$("#review_for_movie_<%= @review.movie_id %>").html("<%= escape_javascript(render :partial => 'review', :object => @review) %>")

app/views/reviews/index.html.erb
<%= render :partial => 'review', :collection => @reviews %>

app/views/reviews/update.js.erb
$("#review_for_movie_<%= @review.movie_id %>").html("<%= escape_javascript(render :partial => 'review', :object => @review) %>")